In [5]:
import numpy as np

In [6]:
arr1 = np.array([1,2,3,4])
arr1.dtype

dtype('int64')

In [7]:
arr2 = np.array([1,2,3,4], dtype='float64')
arr2.dtype

dtype('float64')

In [9]:
arr1.astype(np.float64)

array([1., 2., 3., 4.])

In [13]:
arr3 = np.array([0,1,2,3,4])
arr3 = arr3.astype(np.bool_)
arr3

array([False,  True,  True,  True,  True])

In [15]:
arr3 = np.array([0,1,2,3,4])
arr3 = arr3.astype(np.string_)
arr3

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [16]:
arr3 = np.array(['0','1','2','3','4'])
arr3 = arr3.astype(np.int8)
arr3

array([0, 1, 2, 3, 4], dtype=int8)

In [17]:
arr3 = np.array(['hola','1','2','3','4'])
arr3 = arr3.astype(np.int8)
arr3

ValueError: invalid literal for int() with base 10: 'hola'

**hola no es un tipo de dato int, tirará un error**