In [1]:
import numpy as np

In [2]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((10, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((10, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.linspace(0, 10, 30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
np.random.rand(4)

array([0.1839306 , 0.14213817, 0.63519146, 0.18357176])

In [44]:
np.random.rand(4, 4)

array([[0.24378987, 0.08810574, 0.95306474, 0.44201161],
       [0.83274946, 0.86033623, 0.75839925, 0.77842456],
       [0.73444812, 0.12909737, 0.58359369, 0.65065834],
       [0.6910641 , 0.72264413, 0.41859612, 0.11297567]])

In [45]:
np.random.randint(1, 15)

12

In [50]:
np.random.randint(1, 100, (10, 10))

array([[88,  5, 43, 59, 22, 44, 75, 61, 80, 99],
       [85, 30, 19, 62, 15, 69, 85, 72, 81, 25],
       [46, 92, 89, 70,  4, 56, 73, 36, 50, 84],
       [55,  2, 29, 82, 92, 98, 43, 70,  5, 64],
       [91,  4, 13, 99, 76, 74, 87, 66, 11, 23],
       [ 4, 54, 21, 27, 24, 16, 79, 20,  9, 81],
       [57, 99, 19, 54, 84,  8,  9,  8, 86, 62],
       [65, 39, 17, 78, 52, 38, 77, 95,  2, 11],
       [ 5, 96, 58, 81, 22, 21, 25, 14, 43, 94],
       [24, 70, 74,  4, 72, 57, 66, 43, 65, 46]])