In [2]:
import numpy as np

In [4]:
arr = np.random.randint(1, 10, (3, 2))

In [5]:
arr.shape

(3, 2)

In [7]:
arr

array([[9, 4],
       [5, 5],
       [3, 1]])

In [6]:
arr.reshape(1, 6)

array([[9, 4, 5, 5, 3, 1]])

In [8]:
arr.reshape(2, 3)

array([[9, 4, 5],
       [5, 3, 1]])

In [9]:
np.reshape(arr, (1, 6))

array([[9, 4, 5, 5, 3, 1]])

In [10]:
arr

array([[9, 4],
       [5, 5],
       [3, 1]])

In [11]:
np.reshape(arr, (2, 3), 'C')

array([[9, 4, 5],
       [5, 3, 1]])

In [12]:
np.reshape(arr, (2, 3), 'F')

array([[9, 3, 5],
       [5, 4, 1]])

In [13]:
np.reshape(arr, (2, 3), 'A')

array([[9, 4, 5],
       [5, 3, 1]])

# Reto generar un error haciendo un reshape no valido (que no respete la cantidad de elementos)

In [17]:
reto = np.random.randint(1, 100, (5, 5))

In [18]:
reto

array([[20, 71, 22, 16,  7],
       [ 2, 79, 27, 39,  3],
       [42, 60, 13, 44, 99],
       [73,  7, 60, 22, 28],
       [33, 39, 74, 57, 33]])

In [20]:
reto.reshape(25, 25)

ValueError: cannot reshape array of size 25 into shape (25,25)