In [4]:
import numpy as np

In [5]:
arr = np.random.randint(1, 20, 10)

In [7]:
matriz = arr.reshape(2, 5)
matriz

array([[ 5,  8, 18,  3, 11],
       [ 9,  1,  1, 11,  3]])

In [8]:
arr.max()

18

In [16]:
#El argumento indica el eje en donde buscara el maximo (filas)
matriz.max(1)

array([18, 11])

In [17]:
#El argumento indica el eje en donde buscara el maximo (columnas)
matriz.max(0)

array([ 9,  8, 18, 11, 11])

In [14]:
#indica el indice en donde se encuentra el maximo
arr.argmax()

2