In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 20, 10)

In [3]:
matriz = arr.reshape(2, 5)
matriz

array([[ 8,  2,  3, 13, 13],
       [ 3, 18,  8,  7,  1]])

In [4]:
arr.max()

18

In [5]:
#El argumento indica el eje en donde buscara el maximo (filas)
matriz.max(1)

array([13, 18])

In [6]:
#El argumento indica el eje en donde buscara el maximo (columnas)
matriz.max(0)

array([ 8, 18,  8, 13, 13])

In [7]:
#indica el indice en donde se encuentra el maximo
arr.argmax()

6

In [8]:
matriz.argmax(0)

array([0, 1, 1, 0, 0])

In [9]:
arr.min()

1

In [10]:
matriz.min(0)

array([3, 2, 3, 7, 1])

In [11]:
arr.argmin()

9

In [12]:
matriz.argmin(1)

array([1, 4])

In [13]:
arr

array([ 8,  2,  3, 13, 13,  3, 18,  8,  7,  1])

# ptp indica la diferencia entre el valor menor y el mayor en el array

In [14]:
arr.ptp()

17

In [15]:
matriz.ptp()

17

In [16]:
matriz.ptp(0)

array([ 5, 16,  5,  6, 12])

In [22]:
arr.sort()
arr

array([ 1,  2,  3,  3,  7,  8,  8, 13, 13, 18])

In [23]:
np.percentile(arr, 50)

7.5

In [24]:
np.median(arr)

7.5

In [25]:
np.median(matriz, 1)

array([ 3., 13.])

In [27]:
np.std(arr)

5.332916650389353

In [28]:
np.var(arr)

28.439999999999998

In [29]:
np.mean(arr)

7.6

In [35]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

In [36]:
np.concatenate((a, b),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [37]:
a.ndim

2

In [38]:
b.ndim

1

In [39]:
b = np.expand_dims(b, axis=0)

In [40]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
b

array([[5, 6]])

In [41]:
np.concatenate((a, b),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [44]:
b

array([[5, 6]])

# Para poder concatenar necesitamos la transpuesta de b

In [45]:
b.T

array([[5],
       [6]])

In [43]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])