In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arr = np.array(lista)

In [6]:
type(arr)

numpy.ndarray

In [7]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[1]

2

In [11]:
arr[0] + arr[5]

7

In [12]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
matriz[0, 2]

3

In [14]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [17]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[::3]

array([1, 4, 7])

In [20]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [21]:

matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])

# H1 Challenge: Expplore a 3x3 matrix